# veri_tabani.py
# KPSS Tarih Genişletilmiş Soru ve Konu Veritabanı

KPSS_TUM_KONULAR = {
    "İslamiyet Öncesi Türk Tarihi": {
        "ozet": "Türk adının geçtiği ilk milli kaynak Orhun Abideleri (Göktürkler), ilk yabancı kaynak ise Çin yıllıklaridir.\n\n• Asya Hun Devleti: Bilinen ilk teşkilatlı Türk devleti. En parlak dönemi Mete Han dönemidir. Mete Han 'Onlu Sistemi' kurmuş ve Orta Asya'daki tüm Türk boylarını tek bayrak altında toplamıştır.\n• Kavimler Göçü: Balamir önderliğinde Avrupa'ya göç edilmiş, Avrupa Hun Devleti kurulmuştur. En güçlü dönemi Attila (Tanrının Kırbacı) dönemidir.\n• I. Göktürk: Bumin Kağan kurdu. Türk adıyla kurulan ilk devlettir.\n• II. Göktürk (Kutluk): Kutluk Kağan kurdu. Orhun Abideleri (Bilge Kağan, Kültigin, Tonyukuk) bu dönemde dikildi.\n• Uygurlar: Bögü Kağan döneminde Maniheizm'i benimsediler. Savaşçılık özelliklerini kaybedip tarım, mimari ve matbaada geliştiler. Yerleşik hayata geçen ilk Türk devletidir.\n• Hazarlar: Museviliği kabul eden ilk ve tek Türk devletidir. Ülkelerinde farklı dinlere inananlar barış içinde yaşamış, bu döneme 'Hazar Barış Çağı' denmiştir.",
        "sorular": [
            {"soru": "Tarihte 'Türk' adıyla kurulan ilk devlet aşağıdakilerden hangisidir?", "secenekler": ["Asya Hun", "Göktürkler", "Uygurlar", "Karahanlılar"], "cevap": "Göktürkler"},
            {"soru": "Yerleşik hayata geçerek kalıcı mimari eserler bırakan, matbaa ve kağıdı kullanan ilk Türk devleti hangisidir?", "secenekler": ["Hazarlar", "Karluklar", "Uygurlar", "Avarlar"], "cevap": "Uygurlar"},
            {"soru": "Dünya harp tarihine yön veren 'Onlu Ordu Sistemi'ni kuran Türk hükümdarı kimdir?", "secenekler": ["Teoman", "Mete Han", "Attila", "Bumin Kağan"], "cevap": "Mete Han"},
            {"soru": "Avrupa'da devlet kurarak Roma İmparatorluğu'na diz çöktüren ve 'Tanrının Kırbacı' unvanını alan hükümdar kimdir?", "secenekler": ["Balamir", "Uldız", "Attila", "Rua"], "cevap": "Attila"},
            {"soru": "Museviliği resmi din olarak kabul eden tek Türk devleti aşağıdakilerden hangisidir?", "secenekler": ["Uygurlar", "Hazarlar", "Peçenekler", "Kıpçaklar"], "cevap": "Hazarlar"}
        ]
    },
    "İlk Türk-İslam Devletleri": {
        "ozet": "Talas Savaşı (751) ile Türkler kitleler halinde İslamiyet'i kabul etmeye başladı (İslamiyet'i kabul eden ilk Türk boyu Karluklar'dır).\n\n• Karahanlılar: Orta Asya'da kurulan ilk Türk-İslam devletidir. Kurucusu Bilge Kül Kadir Han'dır. Resmi dilleri Türkçedir. Satuk Buğra Han döneminde İslamiyet resmi din oldu.\n• Gazneliler: Kurucusu Alp Tigin'dir. En parlak dönem Gazneli Mahmut'tur. Hindistan'a 17 sefer yaparak İslamiyet'i yaymıştır ve 'Sultan' unvanını kullanan ilk Türk hükümdarıdır.\n• Büyük Selçuklu Devleti: 1040 Dandanakan Savaşı ile Gaznelileri yenerek kuruldu. 1071 Malazgirt Meydan Muharebesi ile Romen Diyojen mağlup edildi, Anadolu'nun kapıları Türklere açıldı.\n• Tolunoğulları ve Akşitler: Mısır'da kurulan ilk Türk İslam devletleridir. Yöneticileri Türk, halkı Arap olduğu için kısa sürede yıkılmışlardır.",
        "sorular": [
            {"soru": "Orta Asya'da İslamiyet'i kabul eden ilk büyük Türk devleti hangisidir?", "secenekler": ["Gazneliler", "Büyük Selçuklu", "Karahanlılar", "Tolunoğulları"], "cevap": "Karahanlılar"},
            {"soru": "Anadolu'nun kapılarını Türklere açan 1071 Malazgirt Savaşı'nı kazanan Selçuklu Sultanı kimdir?", "secenekler": ["Tuğrul Bey", "Alparslan", "Melikşah", "Sencer"], "cevap": "Alparslan"},
            {"soru": "Sultan unvanını kullanan ilk Türk İslam hükümdarı kimdir?", "secenekler": ["Tuğrul Bey", "Gazneli Mahmut", "Satuk Buğra Han", "Alparslan"], "cevap": "Gazneli Mahmut"},
            {"soru": "Mısır'da kurulan ilk Türk-İslam devleti aşağıdakilerden hangisidir?", "secenekler": ["Memlükler", "Eyyubiler", "Tolunoğulları", "Akşitler"], "cevap": "Tolunoğulları"},
            {"soru": "Büyük Selçuklu Devleti'nin resmen kurulduğu ve Gaznelilerin yıkılış sürecine girdiği savaş hangisidir?", "secenekler": ["Katvan", "Dandanakan", "Pasinler", "Malazgirt"], "cevap": "Dandanakan"}
        ]
    },
    "Türkiye Selçuklu Devleti ve Beylikler": {
        "ozet": "Anadolu'da kurulan ilk beylikler (Saltuklular, Mengücekler, Danişmentliler) Malazgirt sonrası Türkleşmeyi sağlamıştır.\n\n• Türkiye Selçuklu: Süleyman Şah tarafından İznik merkezli kuruldu. I. Haçlı Seferi sonrası başkent Konya'ya taşındı.\n• Miryokefalon Savaşı (1176): II. Kılıçarslan döneminde Bizans mağlup edildi. Anadolu'nun kesin olarak Türk yurdu olduğu kanıtlandı ('Yurttutan' savaşı).\n• Alaeddin Keykubat Dönemi: Devletin en parlak zamanıdır. Deniz aşırı seferler yapılmış, Alanya alınmıştır.\n• Yıkılış: 1243 Kösedağ Savaşı'nda İlhanlı (Moğol) devletine yenilerek dağılma sürecine girmişler ve İkinci Beylikler dönemi (Osmanoğulları, Karamanoğulları vb.) başlamıştır.",
        "sorular": [
            {"soru": "Anadolu'nun kesin olarak Türk yurdu olmasını sağlayan ve 'Yurttutan' olarak bilinen savaş hangisidir?", "secenekler": ["Pasinler", "Kösedağ", "Dandanakan", "Miryokefalon"], "cevap": "Miryokefalon"},
            {"soru": "Türkiye Selçuklu Devleti'nin en parlak dönemi hangi hükümdar zamanında yaşanmıştır?", "secenekler": ["Süleyman Şah", "I. Mesut", "II. Kılıçarslan", "I. Alaeddin Keykubat"], "cevap": "I. Alaeddin Keykubat"},
            {"soru": "Anadolu Selçuklu Devleti'nin dağılma sürecine girmesine neden olan Moğol istilası savaşı hangisidir?", "secenekler": ["Yassıçemen", "Kösedağ", "Katvan", "Ankara"], "cevap": "Kösedağ"},
            {"soru": "Erzurum ve çevresinde kurulan, Anadolu'daki ilk Türk beyliği aşağıdakilerden hangisidir?", "secenekler": ["Danişmentliler", "Mengücekler", "Saltuklular", "Artuklular"], "cevap": "Saltuklular"}
        ]
    },
    "Osmanlı Devleti Kuruluş Dönemi": {
        "ozet": "1299'da Osman Bey ile başlayan süreç imparatorluğa dönüşmüştür.\n\n• Osman Bey: Bağımsızlığını ilan etti, ilk bakır para basıldı. İlk Osmanlı-Bizans savaşı (Koyunhisar) kazanıldı.\n• Orhan Bey: Bursa'yı alıp başkent yaptı. İlk düzenli ordu (Yaya ve Müsellem), ilk divan teşkilatı ve ilk medrese kuruldu.\n• I. Murat: İlk Osmanlı-Haçlı savaşı Sırpsındığı yapıldı. Yeniçeri ocağı, Devşirme sistemi ve Tımar sistemi kuruldu.\n• Yıldırım Bayezid: İstanbul'u kuşatan ilk padişahtır. 1396 Niğbolu Savaşı'nda Haçlıları ağır yenilgiye uğrattı. Ancak 1402 Ankara Savaşı'nda Timur'a yenilince devlet 11 yıl süren 'Fetret Devri'ne girdi.\n• Çelebi Mehmet: Fetret devrine son verdiği için devletin 'İkinci Kurucusu' sayılır.",
        "sorular": [
            {"soru": "Osmanlı Devleti'nde ilk düzenli orduyu kuran ve devleti beylikten devlete taşıyan padişah kimdir?", "secenekler": ["Osman Bey", "Orhan Bey", "I. Murat", "Yıldırım Bayezid"], "cevap": "Orhan Bey"},
            {"soru": "Osmanlı Devleti ile Haçlılar arasında yapılan ilk savaş aşağıdakilerden hangisidir?", "secenekler": ["Sırpsındığı", "I. Kosova", "Varna", "Niğbolu"], "cevap": "Sırpsındığı"},
            {"soru": "Ankara Savaşı'nda (1402) Timur'a yenilerek devletin Fetret Devri'ne girmesine sebep olan padişah kimdir?", "secenekler": ["I. Murat", "II. Murat", "Yıldırım Bayezid", "Çelebi Mehmet"], "cevap": "Yıldırım Bayezid"},
            {"soru": "Fetret Devri'ne son vererek Osmanlı Devleti'nin ikinci kurucusu unvanını alan padişah kimdir?", "secenekler": ["Orhan Bey", "I. Murat", "II. Murat", "I. Mehmet (Çelebi)"], "cevap": "I. Mehmet (Çelebi)"},
            {"soru": "Yeniçeri Ocağı'nı ve Pençik sistemini kuran Osmanlı padişahı hangisidir?", "secenekler": ["Osman Bey", "Orhan Bey", "I. Murat", "Fatih Sultan Mehmet"], "cevap": "I. Murat"}
        ]
    },
    "Osmanlı Devleti Yükselme Dönemi": {
        "ozet": "1453 İstanbul fethiyle başlayıp 1579 Sokullu Mehmet Paşa'nın ölümüne kadar süren zirve dönemidir.\n\n• Fatih Sultan Mehmet: İstanbul fethiyle Orta Çağ kapanıp Yeni Çağ başladı. Anadolu ve Rumeli toprak bütünlüğü sağlandı. Topkapı Sarayı yapıldı, Kırım alınarak Karadeniz Türk gölü oldu.\n• II. Bayezid: Cem Sultan olayı yüzünden Batı'da seferler durma noktasına gelmiştir.\n• Yavuz Sultan Selim: Doğudaki tehlikeleri bitirdi. Çaldıran Savaşı ile Safeviler, Mercidabık ve Ridaniye ile Memlükler yıkıldı. Halifelik Osmanlı'ya geçti ve Kutsal Emanetler İstanbul'a getirildi.\n• Kanuni Sultan Süleyman: En uzun süre (46 yıl) tahtta kalan padişahtır. Belgrad ve Rodos alındı, Mohaç Meydan Muharebesi'nde Macaristan fethedildi. Preveze Deniz Zaferi (1538) ile Akdeniz Türk gölü oldu.",
        "sorular": [
            {"soru": "Halifelik makamının Osmanlı Devleti'ne geçmesini sağlayan savaş hangisidir?", "secenekler": ["Otlukbeli", "Çaldıran", "Mercidabık", "Ridaniye"], "cevap": "Ridaniye"},
            {"soru": "Akdeniz'in Türk gölü haline gelmesini sağlayan ve Barbaros Hayreddin Paşa'nın komuta ettiği deniz savaşı hangisidir?", "secenekler": ["İnebahtı", "Preveze", "Cerbe", "Çeşme"], "cevap": "Preveze"},
            {"soru": "Karadeniz'in bir Türk gölü olmasını sağlayan fetih aşağıdakilerden hangisidir?", "secenekler": ["İstanbul'un Fethi", "Amasra'nın Alınması", "Kırım'ın Fethi", "Trabzon'un Fethi"], "cevap": "Kırım'ın Fethi"},
            {"soru": "Dünya tarihinin en kısa süren meydan muharebelerinden biri olan ve Macaristan'ın fethiyle sonuçlanan savaş hangisidir?", "secenekler": ["Mohaç", "Zigetvar", "Viyana Kuşatması", "Haçova"], "cevap": "Mohaç"},
            {"soru": "Osmanlı Devleti'nde ilk altın parayı bastıran padişah kimdir?", "secenekler": ["Orhan Bey", "Fatih Sultan Mehmet", "Yavuz Sultan Selim", "Kanuni Sultan Süleyman"], "cevap": "Fatih Sultan Mehmet"}
        ]
    },
    "Osmanlı Kültür ve Medeniyeti": {
        "ozet": "Devletin merkezi Padişah ve Topkapı Sarayı'dır.\n\n• Seyfiye Sınıfı: Yönetim ve askeriyeden sorumlu sınıf (Sadrazam, Yeniçeri Ağası, Beylerbeyi, Sancakbeyi).\n• İlmiye Sınıfı: Din, eğitim ve hukuk işlerinden sorumlu sınıf (Şeyhülislam, Kazasker, Kadı, Müderris).\n• Kalemiye Sınıfı: Bürokrasi, maliye ve yazışmalardan sorumlu sınıf (Nişancı, Defterdar, Reisülküttap).\n• Tımar Sistemi: Devletin, mülkiyeti kendisine ait olan toprağı maaş karşılığı memur veya askere bırakmasıdır. Üretime süreklilik, devlete bedavadan asker (Cebelü) sağlanırdı.\n• Vergiler: Öşür (Müslüman'dan alınan 1/10 ürün vergisi), Haraç (Gayrimüslim ürün vergisi), Cizye (Gayrimüslim erkeklerden askerlik yapmamaları karşılığında alınan kelle vergisi), Avarız (Olağanüstü hal vergisi).",
        "sorular": [
            {"soru": "Osmanlı Devleti'nde Kadı ve Müderrislerin atamasını yapan, eğitim ve adalet işlerinden sorumlu divan üyesi kimdir?", "secenekler": ["Nişancı", "Defterdar", "Kazasker", "Şeyhülislam"], "cevap": "Kazasker"},
            {"soru": "Gayrimüslim erkeklerden askerlik yapmamaları karşılığında alınan vergi hangisidir?", "secenekler": ["Cizye", "Haraç", "Avarız", "Ağnam"], "cevap": "Cizye"},
            {"soru": "Osmanlı'da fethedilen toprakları tapu tahrir defterlerine kaydeden, dirlik topraklarının dağıtımını yapan görevli kimdir?", "secenekler": ["Sadrazam", "Defterdar", "Nişancı", "Reisülküttap"], "cevap": "Nişancı"},
            {"soru": "Aşağıdakilerden hangisi Tımar sisteminin devlete sağladığı faydalardan biri DEĞİLDİR?", "secenekler": ["Üretimde süreklilik sağlanması", "Hazineye nakit para girişinin artması", "Taşrada güvenliğin sağlanması", "Masrafsız bir ordunun yetişmesi"], "cevap": "Hazineye nakit para girişinin artması"},
            {"soru": "Osmanlı toplumunda yönetenler grubunda yer alan İlmiye sınıfının en üst rütbeli yöneticisi kimdir?", "secenekler": ["Kazasker", "Şeyhülislam", "Müderris", "Kadı"], "cevap": "Şeyhülislam"}
        ]
    },
    "Osmanlı Duraklama Dönemi (17. Yüzyıl)": {
        "ozet": "1579 Sokullu Mehmet Paşa'nın ölümüyle başlar, 1699 Karlofça Antlaşması ile biter.\n\n• Bu dönem ıslahatlarında BATI ETKİSİ YOKTUR. Yükselme dönemi (Kanuni devri) örnek alınmış, sorunların temeline inilmeyip baskı ve şiddet uygulanmıştır.\n• Kasr-ı Şirin Antlaşması (1639): İran ile yapılmıştır, günümüz Türkiye-İran sınırını büyük ölçüde çizen antlaşmadır.\n• Karlofça Antlaşması (1699): Kutsal İttifak devletlerine karşı kaybedilen savaşlar sonucunda imzalandı. Osmanlı'nın Batı'da İLK KEZ büyük çapta toprak kaybettiği antlaşmadır.\n• Önemli Islahatçılar: Tarhuncu Ahmet Paşa (İlk denk bütçe), Genç Osman (Yeniçeri ocağını kaldırmayı düşünen ilk padişah, bu yüzden öldürüldü), IV. Murat (İçki/tütün yasağı, Koçi Bey Risalesi).",
        "sorular": [
            {"soru": "Osmanlı Devleti'nin Batı'da ilk kez büyük çapta toprak kaybettiği ve Duraklama dönemini bitirip Gerileme dönemini başlatan antlaşma hangisidir?", "secenekler": ["Zitvatorok", "Karlofça", "Pasarofça", "Vasvar"], "cevap": "Karlofça"},
            {"soru": "Günümüz Türkiye-İran sınırını büyük ölçüde belirleyen 17. yüzyıl antlaşması aşağıdakilerden hangisidir?", "secenekler": ["Ferhat Paşa", "Nasuh Paşa", "Serav", "Kasr-ı Şirin"], "cevap": "Kasr-ı Şirin"},
            {"soru": "Osmanlı tarihinde Yeniçeri Ocağı'nı kaldırmayı düşünen ancak isyan sonucu öldürülen ilk padişah kimdir?", "secenekler": ["II. Osman (Genç)", "IV. Murat", "III. Selim", "II. Mahmut"], "cevap": "II. Osman (Genç)"},
            {"soru": "Aşağıdakilerden hangisi 17. Yüzyıl (Duraklama Dönemi) ıslahatlarının genel özelliklerinden biri DEĞİLDİR?", "secenekler": ["Baskı ve şiddet yoluyla benimsetilmeye çalışılması", "Avrupa'nın (Batı'nın) örnek alınması", "Sorunların kökenine inilmemesi", "Kişilere bağlı kalıp devlet politikası haline gelememesi"], "cevap": "Avrupa'nın (Batı'nın) örnek alınması"},
            {"soru": "Saray masraflarını kısıp modern anlamda ilk denk bütçeyi hazırlayan 17. yüzyıl devlet adamı kimdir?", "secenekler": ["Köprülü Mehmet Paşa", "Kuyucu Murat Paşa", "Tarhuncu Ahmet Paşa", "Sokullu Mehmet Paşa"], "cevap": "Tarhuncu Ahmet Paşa"}
        ]
    },
    "Osmanlı Gerileme Dönemi (18. Yüzyıl)": {
        "ozet": "1699 Karlofça ile başlar, 1792 Yaş Antlaşması ile biter.\n\n• Bu dönemde BATI'NIN ÜSTÜNLÜĞÜ KABUL EDİLMİŞ ve Avrupa tarzı ıslahatlar başlamıştır.\n• Lale Devri (1718-1730): Pasarofça Antlaşması ile başlar, Patrona Halil İsyanı ile biter. Askeri ıslahat YOKTUR. Matbaa (İbrahim Müteferrika), çiçek aşısı, ilk itfaiye ocağı (Tulumbacılar) bu dönemdedir.\n• Küçük Kaynarca Antlaşması (1774): Rusya ile yapıldı. Kırım bağımsız oldu. İlk defa halkı tamamen Türk ve Müslüman olan bir toprak kaybedildi. Rusya'ya ilk kez kapitülasyon verildi.\n• Nizam-ı Cedit: III. Selim'in yaptığı tüm yeniliklere verilen addır. Batı tarzı ilk ordu kurulmuş, bu ordunun masrafları için İrad-ı Cedit hazinesi oluşturulmuştur.",
        "sorular": [
            {"soru": "Osmanlı Devleti'nin Batı'nın üstünlüğünü kabul ederek Avrupa tarzı ıslahatlara başladığı dönem hangisidir?", "secenekler": ["Tanzimat Dönemi", "Meşrutiyet Dönemi", "Lale Devri", "Köprülüler Devri"], "cevap": "Lale Devri"},
            {"soru": "Halkı tamamen Müslüman olan bir toprağın (Kırım) ilk defa kaybedildiği, Osmanlı'yı derinden sarsan antlaşma hangisidir?", "secenekler": ["Karlofça", "Pasarofça", "Küçük Kaynarca", "Belgrad"], "cevap": "Küçük Kaynarca"},
            {"soru": "Aşağıdakilerden hangisi Lale Devri yeniliklerinden biri DEĞİLDİR?", "secenekler": ["İlk Türk matbaasının kurulması", "Çiçek aşısının uygulanması", "Avrupa başkentlerine ilk geçici elçilerin gönderilmesi", "Batı tarzı askeri okulların açılması"], "cevap": "Batı tarzı askeri okulların açılması"},
            {"soru": "III. Selim tarafından kurulan Batı tarzı ordunun adı aşağıdakilerden hangisidir?", "secenekler": ["Sekban-ı Cedit", "Nizam-ı Cedit", "Eşkinci Ocağı", "Asakir-i Mansure-i Muhammediye"], "cevap": "Nizam-ı Cedit"},
            {"soru": "Lale Devri'ne son veren ve padişah III. Ahmet'in tahttan indirilmesine sebep olan isyan hangisidir?", "secenekler": ["Patrona Halil İsyanı", "Kabakçı Mustafa İsyanı", "Çınar Vakası", "Celali İsyanları"], "cevap": "Patrona Halil İsyanı"}
        ]
    },
    "Osmanlı Dağılma Dönemi (19. Yüzyıl)": {
        "ozet": "Fransız İhtilali'nin yaydığı 'Milliyetçilik' akımı nedeniyle azınlık isyanları devleti parçalamıştır. Devlet ayakta kalmak için 'Denge Politikası' izlemiştir.\n\n• Sırp İsyanı: Milliyetçilik akımıyla isyan eden ilk azınlıktır.\n• Yunan İsyanı: Edirne Antlaşması (1829) ile BAĞIMSIZ olan ilk azınlıktır.\n• Tanzimat Fermanı (1839): Padişah ilk defa kendi gücünün üstünde KANUN GÜCÜNÜ kabul etmiştir. Müslüman ve gayrimüslim herkes kanun önünde eşit sayılmıştır.\n• Islahat Fermanı (1856): Sadece gayrimüslimlere yönelik hakları genişleten, Avrupa'nın iç işlerimize karışmasını engellemek için yayınlanan fermandır.\n• I. Meşrutiyet ve Kanun-i Esasi (1876): Genç Osmanlılar (Jön Türkler) etkisiyle II. Abdülhamit ilan etti. Türk tarihinin ilk anayasası yürürlüğe girdi. Halk (kısıtlı da olsa) ilk kez yönetime katıldı.",
        "sorular": [
            {"soru": "Osmanlı Devleti'nde padişahın yetkilerinin ilk kez kanun gücüyle sınırlandığı belge hangisidir?", "secenekler": ["Sened-i İttifak", "Tanzimat Fermanı", "Islahat Fermanı", "Kanun-i Esasi"], "cevap": "Tanzimat Fermanı"},
            {"soru": "Osmanlı Devleti'ne karşı milliyetçilik akımının etkisiyle isyan eden İLK azınlık hangisidir?", "secenekler": ["Yunanlılar", "Bulgarlar", "Ermeniler", "Sırplar"], "cevap": "Sırplar"},
            {"soru": "Osmanlı Devleti'nden ayrılarak bağımsızlığını kazanan İLK azınlık aşağıdakilerden hangisidir?", "secenekler": ["Yunanlılar", "Sırplar", "Romanyalılar", "Arnavutlar"], "cevap": "Yunanlılar"},
            {"soru": "Türk tarihinin ilk anayasası olan ve halkın ilk kez kısıtlı da olsa yönetime katılmasını sağlayan belge hangisidir?", "secenekler": ["Mecelle", "Kanun-i Esasi", "Fatih Kanunnamesi", "Teşkilat-ı Esasiye"], "cevap": "Kanun-i Esasi"},
            {"soru": "Sadece gayrimüslimlerin (azınlıkların) haklarını genişleterek Avrupalı devletlerin Osmanlı'nın iç işlerine karışmasını önlemek amacıyla ilan edilen ferman hangisidir?", "secenekler": ["Tanzimat Fermanı", "Islahat Fermanı", "Sened-i İttifak", "Halepa Fermanı"], "cevap": "Islahat Fermanı"}
        ]
    },
    "20. Yüzyıl Başlarında Osmanlı Devleti": {
        "ozet": "Devletin yıkılış sürecine girdiği ve art arda savaşların yaşandığı dönemdir.\n\n• Trablusgarp Savaşı (1911): İtalya'nın hammadde arayışıyla saldırması sonucu çıktı. Mustafa Kemal gönüllü olarak (Gazeteci Şerif takma adıyla) gidip Derne ve Tobruk'ta savaştı. Uşi Antlaşması ile Kuzey Afrika'daki son toprak kaybedildi.\n• I. Balkan Savaşı: Karadağ, Sırbistan, Yunanistan ve Bulgaristan'ın Osmanlı'ya saldırmasıdır. Osmanlı ağır yenilgi aldı, Midye-Enez hattının batısı kaybedildi.\n• I. Dünya Savaşı (1914-1918): Osmanlı, Almanya'nın yanında İttifak devletleri safında savaşa girdi.\n• Taarruz Cepheleri: Kafkas (Sarıkamış faciası yaşandı, Muş ve Bitlis'i M. Kemal geri aldı) ve Kanal cephesi.\n• Savunma Cepheleri: Çanakkale (Kazanılan tek cephedir, savaşın süresi uzamıştır), Suriye-Filistin, Hicaz-Yemen, Irak.\n• Mondros Ateşkesi (1918): 7. Madde ('Güvenliği tehdit eden her yer işgal edilebilir') ile Anadolu işgallere açık hale geldi.",
        "sorular": [
            {"soru": "Osmanlı Devleti'nin Kuzey Afrika'daki siyasi varlığını sona erdiren antlaşma hangisidir?", "secenekler": ["Mondros", "Lozan", "Uşi", "Sevr"], "cevap": "Uşi"},
            {"soru": "Mustafa Kemal'in 'Gazeteci Şerif' takma adıyla gönüllü olarak gidip yerel halkı örgütlediği savaş hangisidir?", "secenekler": ["I. Balkan Savaşı", "Trablusgarp Savaşı", "Çanakkale Savaşı", "Kafkas Cephesi"], "cevap": "Trablusgarp Savaşı"},
            {"soru": "I. Dünya Savaşı'nda Osmanlı Devleti'nin taarruz (saldırı) amacıyla açtığı cepheler hangileridir?", "secenekler": ["Kafkas ve Kanal", "Çanakkale ve Suriye", "Hicaz ve Yemen", "Makedonya ve Galiçya"], "cevap": "Kafkas ve Kanal"},
            {"soru": "Mondros Ateşkes Antlaşması'nın Anadolu'nun işgaline hukuki zemin hazırlayan en tehlikeli maddesi hangisidir?", "secenekler": ["24. Madde", "1. Madde", "7. Madde", "12. Madde"], "cevap": "7. Madde"},
            {"soru": "I. Dünya Savaşı'nda Osmanlı Devleti'nin zaferle kapattığı tek cephe aşağıdakilerden hangisidir?", "secenekler": ["Irak", "Kafkas", "Kanal", "Çanakkale"], "cevap": "Çanakkale"}
        ]
    },
    "Milli Mücadele Hazırlık Dönemi": {
        "ozet": "Mustafa Kemal'in 19 Mayıs 1919'da Samsun'a çıkmasıyla başlar.\n\n• Havza Genelgesi: İşgallere karşı protesto ve mitingler yapılması istendi (Milli bilincin uyanması).\n• Amasya Genelgesi: Kurtuluş Savaşı'nın amacı, gerekçesi ve yöntemi belirtildi. Milli egemenliğe dayalı yeni bir devletin ilk işaretidir.\n• Erzurum Kongresi: Toplanış bakımından bölgesel, aldığı kararlar bakımından ulusaldır. İlk kez milli sınırlardan (Misak-ı Milli) bahsedildi, manda ve himaye ilk kez reddedildi.\n• Sivas Kongresi: Her yönüyle ulusal bir kongredir. Manda ve himaye KESİN olarak reddedildi. Tüm yararlı cemiyetler tek çatı altında (Anadolu ve Rumeli Müdafaa-i Hukuk Cemiyeti) birleştirildi.\n• I. TBMM (23 Nisan 1920): Kurucu meclistir. Otoritesini sağlamak için Hıyanet-i Vataniye Kanunu'nu çıkardı ve İstiklal Mahkemeleri'ni kurdu.",
        "sorular": [
            {"soru": "Kurtuluş Savaşı'nın gerekçesi, amacı ve yönteminin belirtildiği belge hangisidir?", "secenekler": ["Havza Genelgesi", "Amasya Genelgesi", "Erzurum Kongresi", "Misak-ı Milli"], "cevap": "Amasya Genelgesi"},
            {"soru": "Manda ve himayenin kesin olarak reddedildiği, milli cemiyetlerin birleştirildiği kongre hangisidir?", "secenekler": ["Erzurum", "Sivas", "Alaşehir", "Balıkesir"], "cevap": "Sivas"},
            {"soru": "Toplanış şekli bakımından bölgesel, aldığı kararlar bakımından ulusal olan kongre hangisidir?", "secenekler": ["Sivas Kongresi", "Erzurum Kongresi", "Nazilli Kongresi", "Pozantı Kongresi"], "cevap": "Erzurum Kongresi"},
            {"soru": "I. TBMM'nin ayaklanmaları bastırmak ve otoritesini sağlamak amacıyla çıkardığı kanun hangisidir?", "secenekler": ["Takrir-i Sükun", "Teşkilat-ı Esasiye", "Hıyanet-i Vataniye", "Tekalif-i Milliye"], "cevap": "Hıyanet-i Vataniye"},
            {"soru": "Milli mücadelenin haklılığını dünya kamuoyuna duyuran ilk uluslararası belge aşağıdakilerden hangisidir?", "secenekler": ["Amiral Bristol Raporu", "Milne Hattı", "General Harbord Raporu", "Wilson İlkeleri"], "cevap": "Amiral Bristol Raporu"}
        ]
    },
    "Kurtuluş Savaşı Muharebeler Dönemi": {
        "ozet": "Doğu, Güney ve Batı olmak üzere üç cephede savaşılmıştır.\n\n• Doğu Cephesi: Kazım Karabekir (15. Kolordu) komutasında Ermenilerle savaşıldı. Gümrü Antlaşması ile kapandı (TBMM'nin ilk siyasi/askeri başarısı).\n• Güney Cephesi: Düzenli ordu yoktur, Kuvay-ı Milliye birlikleri Fransız ve Ermenilere karşı savaştı. Ankara Antlaşması (1921) ile kapandı.\n• Batı Cephesi: Yunanlılara karşı düzenli ordunun savaştığı ana cephedir.\n- I. İnönü: Düzenli ordunun ilk zaferidir. Sonucunda İstiklal Marşı kabul edildi, Londra Konferansı toplandı, Moskova Antlaşması yapıldı.\n- II. İnönü: 'Siz orada yalnız düşmanı değil, milletin makus talihini de yendiniz' (M. Kemal).\n- Kütahya-Eskişehir: Düzenli ordunun tek yenilgisidir.\n- Sakarya: Son savunma savaşıdır. M. Kemal'e Gazi ve Mareşal unvanı verildi.\n- Büyük Taarruz: Yunan ordusu denize döküldü, silahlı mücadele bitti.\n• Mudanya Ateşkesi (1922) ile sıcak çatışma sona erdi.",
        "sorular": [
            {"soru": "TBMM'nin uluslararası alanda kazandığı ilk askeri ve siyasi başarı olan antlaşma hangisidir?", "secenekler": ["Gümrü", "Moskova", "Ankara", "Kars"], "cevap": "Gümrü"},
            {"soru": "Mustafa Kemal'e 'Gazi' unvanı ve 'Mareşal' rütbesi hangi savaştan sonra TBMM tarafından verilmiştir?", "secenekler": ["Çanakkale", "I. İnönü", "Sakarya", "Büyük Taarruz"], "cevap": "Sakarya"},
            {"soru": "Düzenli ordunun Batı Cephesi'nde kazandığı ilk zafer aşağıdakilerden hangisidir?", "secenekler": ["I. İnönü", "II. İnönü", "Sakarya", "Büyük Taarruz"], "cevap": "I. İnönü"},
            {"soru": "Kurtuluş Savaşı'nın silahlı mücadele dönemini sona erdiren diplomatik belge hangisidir?", "secenekler": ["Lozan Barış Antlaşması", "Mudanya Ateşkes Antlaşması", "Moskova Antlaşması", "Ankara Antlaşması"], "cevap": "Mudanya Ateşkes Antlaşması"},
            {"soru": "Güney cephesinde hangi devlete karşı mücadele edilmiştir?", "secenekler": ["İngiltere", "İtalya", "Fransa", "Yunanistan"], "cevap": "Fransa"}
        ]
    },
    "Atatürk İlkeleri ve İnkılapları": {
        "ozet": "Yeni devletin temelleri atılmıştır.\n\n• Siyasi İnkılaplar: Saltanatın Kaldırılması (1922 - Laiklik yolunda ilk adım), Cumhuriyetin İlanı (1923), Halifeliğin Kaldırılması (1924).\n• Hukuk İnkılapları: 1926 Türk Medeni Kanunu (İsviçre'den alındı. Din ve ırk farkı gözetilmeden hukuk birliği sağlandı. Kadınlara sosyal ve ekonomik eşitlik geldi ancak SİYASİ HAK VERİLMEDİ).\n• Eğitim İnkılapları: Tevhid-i Tedrisat (1924 - Eğitimde birlik sağlandı), Yeni Türk Harflerinin Kabulü (1928), Millet Mekteplerinin Açılması.\n• İlkeler:\n- Cumhuriyetçilik: Milli egemenlik, meclis, çok partili hayat.\n- Milliyetçilik: Bağımsızlık, milli tarih, milli dil.\n- Halkçılık: Eşitlik, ayrıcalıkların reddi (Soyadı Kanunu).\n- Laiklik: Akıl, bilim, din ve devlet işlerinin ayrılması.\n- Devletçilik: Ekonomik yatırımların devlet eliyle yapılması.",
        "sorular": [
            {"soru": "Hiçbir sınıf ve zümreye ayrıcalık tanımayan, kanun önünde eşitliği savunan Atatürk ilkesi hangisidir?", "secenekler": ["Devletçilik", "Milliyetçilik", "Halkçılık", "Laiklik"], "cevap": "Halkçılık"},
            {"soru": "1924 yılında kabul edilen Tevhid-i Tedrisat Kanunu'nun temel amacı nedir?", "secenekler": ["Arap alfabesini kaldırmak", "Eğitim ve öğretimi birleştirmek", "Medreseleri yeniden açmak", "Üniversite reformu yapmak"], "cevap": "Eğitim ve öğretimi birleştirmek"},
            {"soru": "Aşağıdakilerden hangisi 1926'da kabul edilen Türk Medeni Kanunu ile kadınlara verilen haklardan biri DEĞİLDİR?", "secenekler": ["Miras hakkı", "Seçme ve seçilme hakkı", "İstediği mesleğe girme hakkı", "Boşanma hakkı"], "cevap": "Seçme ve seçilme hakkı"},
            {"soru": "Yeni Türk Devleti'nde laiklik yolunda atılan İLK adım aşağıdakilerden hangisidir?", "secenekler": ["Halifeliğin kaldırılması", "Saltanatın kaldırılması", "Tekke ve zaviyelerin kapatılması", "Medeni Kanun'un kabulü"], "cevap": "Saltanatın kaldırılması"},
            {"soru": "Atatürk'ün 'Devletçilik' ilkesi doğrultusunda ekonomiye yön vermek amacıyla 1933'te hazırlanan plan hangisidir?", "secenekler": ["Birinci Beş Yıllık Sanayi Planı", "Milli Korunma Kanunu", "Teşvik-i Sanayi Kanunu", "Misak-ı İktisadi"], "cevap": "Birinci Beş Yıllık Sanayi Planı"}
        ]
    },
    "Çağdaş Türk ve Dünya Tarihi": {
        "ozet": "20. Yüzyıl dünya siyasetinde büyük değişimler.\n\n• Basmacı Hareketi: Sovyet Rusya işgaline karşı Orta Asya Türklerinin (Özbek, Türkmen vb.) başlattığı direniş hareketidir (Enver Paşa da katılmıştır).\n• II. Dünya Savaşı (1939-1945): Türkiye doğrudan girmemiş, aktif denge politikası izlemiştir (İsmet İnönü dönemi). Ekonomiyi korumak için Milli Korunma Kanunu çıkarılmış, Varlık Vergisi uygulanmıştır.\n• Soğuk Savaş: ABD (NATO) ve SSCB (Varşova Paktı) arasındaki gerilim dönemidir.\n• Türkiye'nin NATO'ya Girişi: 1950'de Kore Savaşı'na asker göndermesi, 1952'de NATO'ya kabul edilmesini sağlamıştır.\n• Kıbrıs Sorunu: 1974'te Bülent Ecevit başbakanlığında Kıbrıs Barış Harekatı ('Ayşe tatile çıksın' parolasıyla) yapılmış, KKTC'nin temelleri atılmıştır.",
        "sorular": [
            {"soru": "Türkiye'nin 1952 yılında NATO'ya üye olarak kabul edilmesinde hangi gelişme doğrudan etkili olmuştur?", "secenekler": ["Kıbrıs Barış Harekatı", "Kore Savaşı'na asker göndermesi", "Balkan Antantı'nı imzalaması", "Sadabat Paktı'na katılması"], "cevap": "Kore Savaşı'na asker göndermesi"},
            {"soru": "Orta Asya'da Rusların sömürgeci politikalarına karşı başlayan bağımsızlık mücadelesi aşağıdakilerden hangisidir?", "secenekler": ["Kuvayımilliye", "Basmacı Hareketi", "Beyaz Ordu İsyanı", "Bolşevik Devrimi"], "cevap": "Basmacı Hareketi"},
            {"soru": "II. Dünya Savaşı sırasında Türkiye'de uygulanan ve ekonomiyi devlet kontrolünde tutmayı amaçlayan kanun hangisidir?", "secenekler": ["Teşvik-i Sanayi", "Milli Korunma Kanunu", "Varlık Vergisi", "Toprak Reformu"], "cevap": "Milli Korunma Kanunu"},
            {"soru": "1974 Kıbrıs Barış Harekatı'nın başlaması için dönemin Dışişleri Bakanı Turan Güneş tarafından bildirilen tarihi parola aşağıdakilerden hangisidir?", "secenekler": ["Ordular İlk Hedefiniz Akdeniz'dir", "Ayşe tatile çıksın", "Yurtta Sulh Cihanda Sulh", "Şafak Vakti"], "cevap": "Ayşe tatile çıksın"},
            {"soru": "SSCB'nin dağılmasıyla bağımsızlığını ilan eden ilk Türk Cumhuriyeti hangisidir?", "secenekler": ["Kazakistan", "Özbekistan", "Azerbaycan", "Kırgızistan"], "cevap": "Azerbaycan"}
        ]
    }
}