name: APK Derleyici

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Python Ayarlari
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Gerekli Kutuphanelerin Kurulumu
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses-dev cmake libffi-dev libssl-dev
          pip install --upgrade buildozer cython==0.29.33 virtualenv

      - name: Buildozer Ayarlari ve Lisans Onayi
        run: |
          rm -f buildozer.spec
          buildozer init
          sed -i 's/title = My Application/title = KPSS Tarih/g' buildozer.spec
          sed -i 's/package.name = myapp/package.name = kpsstarih/g' buildozer.spec
          sed -i 's/package.domain = org.test/package.domain = org.mehmet/g' buildozer.spec
          sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/g' buildozer.spec
          
      - name: APK Derlemeyi Baslat
        run: buildozer -v android debug

      - name: APK Dosyasini İndirilebilir Hale Getir
        uses: actions/upload-artifact@v4
        with:
          name: KpssTarih_Uygulamasi
          path: bin/*.apk
