name: APK Derleyici

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest

    # Hatamı düzelttiğim doğru şalter
    env:
      BUILDOZER_ALLOW_ROOT: "1"

    steps:
      - uses: actions/checkout@v4

      - name: Buildozer Ayarlarını Yap
        run: |
          rm -f buildozer.spec
          # İkinci güvenlik önlemi: init komutuna da "yes" eklendi
          yes | buildozer init
          sed -i 's/^title =.*/title = KPSS Tarih/' buildozer.spec
          sed -i 's/^package.name =.*/package.name = kpsstarih/' buildozer.spec
          sed -i 's/^package.domain =.*/package.domain = org.mehmet/' buildozer.spec
          sed -i 's/# android.accept_sdk_license = False/android.accept_sdk_license = True/' buildozer.spec
          sed -i 's/^android.api =.*/android.api = 33/' buildozer.spec

      - name: APK Derlemeyi Başlat
        run: yes | buildozer -v android debug

      - name: APK Dosyasını İndir
        uses: actions/upload-artifact@v4
        with:
          name: KPSS_Tarih_Uygulamasi
          path: bin/*.apk
